name: Build WebAssembly

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: 'unoplatform/wasm-build:3.0'

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.102
        
    - name: Install .NET Workloads
      shell: pwsh
      run: |
        & dotnet tool install --global --version 1.16.1 uno.check
        & ~/.dotnet/tools/uno-check --ci --fix --non-interactive --verbose

    - name: Build
      run: |
        mkdir -p $GITHUB_WORKSPACE/artifacts
        mkdir -p $GITHUB_WORKSPACE/artifacts/wasm
        cd src/MyApp.Wasm
        dotnet publish -c Release -f net7.0 -p:OverrideTargetFrameworks=net7.0 /bl:/artifacts/mbuild.binlog -o $GITHUB_WORKSPACE/artifacts/wasm

    - uses: actions/upload-artifact@v2
      with:
        name: drop
        path: artifacts